---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: my-app
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: my-app
      spec:
        # 스테이징에서는 1개만 실행
        replicas: 1                
        template:
          spec:
            containers:
              - name: my-app
            # 스테이징에서는 특정 버전 사용
                image: nginx:1.21  
