---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  # 볼륨 특성
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  # 볼륨 정의
  nfs:
    path: /nas/k8s
    server: 192.168.10.14
