# 고정 ClusterIP는 예시입니다. 적용할 클러스터의 Service CIDR 및 기존 할당과 대조하세요.
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip-svc
spec:
  type: ClusterIP
  clusterIP: 10.100.10.10
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
