---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-env-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    # 변수 지정
    env:
    - name: MYVAR
      value: testvalue
